### ISSUE TITLE
TypeError: Cannot read property 'vehicleInfo' of undefined

### ISSUE THREAD

**Issue by larspetter** [blandman/homebridge-carwings#6]
Hi,

Trying to get it working here. Changed the region code and my login to username (old Leaf) got it a step further :)

But it now stops giving me "TypeError: Cannot read property 'vehicleInfo' of undefined"

Running Homebridge 5.3.0 and Node 8.3.0

The login seems to be successfull cause the app on my phone notices that a login has been done on another device.

Any ideas?

Full error:

TypeError: Cannot read property 'vehicleInfo' of undefined
    at getsessionid (/usr/lib/node_modules/carwings/lib/index.js:72:33)
    at p (/usr/lib/node_modules/carwings/lib/index.js:133:33)
    at /usr/lib/node_modules/carwings/lib/index.js:85:12
    at next (native)
    at step (/usr/lib/node_modules/carwings/lib/index.js:42:191)
    at /usr/lib/node_modules/carwings/lib/index.js:42:361
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by larspetter** [comment]
With same login info the pycarwings2 module returns correct information. So it´s got to be something with the node.js script of my install :) 

Taking away the homebridge-carwings plugin from config.json and Homebridge runs just fine..

**Comment by AshMartian** [comment]
Sorry, I do believe the node carwings code is incorrect. I've been busy to
update the source repository. The carwings node code used is from here:
https://github.com/joshperry/carwings

**Comment by larspetter** [comment]
Yes, found it. There are some differences in responses on Leaf models. 

For 2012 EU model seems like the VehicleInfoList-part of the response is not present and you would need to check for that (or just take it away). Of course RemoteAC etc is neither part of the response and the carwings.js script does not check for such..

function getsessionid(profile) {
// return profile.VehicleInfoList.vehicleInfo[0].custom_sessionid;
return profile.vehicleInfo[0].custom_sessionid;
}

function getvin(profile) {
// return profile.VehicleInfoList.vehicleInfo[0].vin;
return profile.vehicleInfo[0].vin;
}
